### ISSUE TITLE
TWP Review Schema notice returns after cache clearing

### ISSUE THREAD

**Issue by michael-cannon** [michael-cannon/testimonials-widget#199]
![screen shot 2016-07-19 at 15 59 56](https://cloud.githubusercontent.com/assets/1872498/16964580/2f877894-4dca-11e6-8879-22bd3269f034.png)

**Comment by subharanjanm** [comment]
Hi @michael-cannon ,

I just cleared the cache in WPEngine settings ( two-three times ) but the TWP schema notice didn't come. 

You might have got the notice due to the TWP plugin upgrade you did recently. Please note that the schema notice shows up when the plugin gets upgraded, the plugin gets deactivated & then activated again.

Please advise.

Thanks,
Subh

**Comment by michael-cannon** [comment]
@subharanjanm ignore for now then
